# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black = '#01060E'
red = '#EA6C73'

green = '#91B362'
yellow = '#F9AF4F'

blue = '#53BDFA'

magenta = '#FAE994'
cyan = '#90E1C6'

white = '#C7C7C7'

# Bright colors
[colors.bright]
black = '#686868'
red = '#F07178'
green = '#C2D94C'
yellow = '#FFB454'
blue = '#59C2FF'
magenta = '#FFEE99'
cyan = '#95E6CB'
white = '#FFFFFF'

[keyboard]
bindings = [
    { key = "Space", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },
    { key = "V", mods = "Control|Shift", mode = "~Vi", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[window]

dimensions = { columns = 140, lines = 40 }
position = { x = 700, y = 400 }
padding = { x = 8, y = 5 }
dynamic_padding = true
opacity = 1.0
title = "bqdong"
dynamic_title = true

[font]
normal = { family = "Maple Mono NF CN" }
size = 13

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "wsl", args = ["-d", "Ubuntu-24.04", "--cd", "/home/bqdong"] }

